"""update table map_points comments

Revision ID: 01399865ea64
Revises: a9fd8df4a188
Create Date: 2025-01-22 14:57:35.544142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01399865ea64'
down_revision: Union[str, None] = 'a9fd8df4a188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_info',
    sa.Column('id', sa.Integer(), nullable=False, comment='id'),
    sa.Column('country_name', sa.String(length=255), nullable=False, comment='国家名称'),
    sa.Column('capital', sa.String(length=255), nullable=True, comment='首都'),
    sa.Column('biggest_city', sa.String(length=255), nullable=True, comment='最大城市'),
    sa.Column('population', sa.String(length=255), nullable=True, comment='人口'),
    sa.Column('en_name', sa.String(length=255), nullable=True, comment='英文名称'),
    sa.Column('continental', sa.String(length=255), nullable=True, comment='所属大洲'),
    sa.Column('district', sa.String(length=255), nullable=True, comment='所属地区'),
    sa.Column('note', sa.String(length=255), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country_info')
    # ### end Alembic commands ###
