"""update table map_points comments

Revision ID: 18f8e43a0cc1
Revises: 8bd29af8fa1c
Create Date: 2024-11-05 00:45:33.293594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '18f8e43a0cc1'
down_revision: Union[str, None] = '8bd29af8fa1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('map_points', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='id',
               existing_comment='履历信息id',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('map_points', 'spot_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='点位名称',
               existing_comment='履历信息id',
               existing_nullable=False)
    op.alter_column('map_points', 'country_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='所属国家',
               existing_comment='履历信息id',
               existing_nullable=True)
    op.alter_column('map_points', 'note',
               existing_type=mysql.VARCHAR(length=255),
               comment='备注',
               existing_comment='履历信息id',
               existing_nullable=True)
    op.alter_column('map_points', 'latitude',
               existing_type=mysql.FLOAT(),
               comment='纬度',
               existing_comment='履历信息id',
               existing_nullable=False)
    op.alter_column('map_points', 'longitude',
               existing_type=mysql.FLOAT(),
               comment='经度',
               existing_comment='履历信息id',
               existing_nullable=False)
    op.alter_column('map_points', 'height',
               existing_type=mysql.FLOAT(),
               comment='高程',
               existing_comment='履历信息id',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('map_points', 'height',
               existing_type=mysql.FLOAT(),
               comment='履历信息id',
               existing_comment='高程',
               existing_nullable=True)
    op.alter_column('map_points', 'longitude',
               existing_type=mysql.FLOAT(),
               comment='履历信息id',
               existing_comment='经度',
               existing_nullable=False)
    op.alter_column('map_points', 'latitude',
               existing_type=mysql.FLOAT(),
               comment='履历信息id',
               existing_comment='纬度',
               existing_nullable=False)
    op.alter_column('map_points', 'note',
               existing_type=mysql.VARCHAR(length=255),
               comment='履历信息id',
               existing_comment='备注',
               existing_nullable=True)
    op.alter_column('map_points', 'country_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='履历信息id',
               existing_comment='所属国家',
               existing_nullable=True)
    op.alter_column('map_points', 'spot_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='履历信息id',
               existing_comment='点位名称',
               existing_nullable=False)
    op.alter_column('map_points', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='履历信息id',
               existing_comment='id',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
