"""update table map_points comments

Revision ID: 4b4d4843568e
Revises: 01399865ea64
Create Date: 2025-02-06 17:23:02.090762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b4d4843568e'
down_revision: Union[str, None] = '01399865ea64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_of_interest',
    sa.Column('id', sa.Integer(), nullable=False, comment='id'),
    sa.Column('latitude', sa.Float(), nullable=False, comment='纬度'),
    sa.Column('longitude', sa.Float(), nullable=False, comment='经度'),
    sa.Column('height', sa.Float(), nullable=True, comment='高程'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='名称'),
    sa.Column('name_en', sa.String(length=255), nullable=True, comment='英文名称'),
    sa.Column('note', sa.String(length=255), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('point_of_interest')
    # ### end Alembic commands ###
