"""first update

Revision ID: 8bd29af8fa1c
Revises: 
Create Date: 2024-11-04 23:38:30.973501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8bd29af8fa1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_points', sa.Column('spot_name', sa.String(length=255), nullable=False, comment='履历信息id'))
    op.add_column('map_points', sa.Column('country_name', sa.String(length=255), nullable=True, comment='履历信息id'))
    op.add_column('map_points', sa.Column('note', sa.String(length=255), nullable=True, comment='履历信息id'))
    op.add_column('map_points', sa.Column('height', sa.Float(), nullable=True, comment='履历信息id'))
    op.alter_column('map_points', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='履历信息id',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('map_points', 'latitude',
               existing_type=mysql.FLOAT(),
               comment='履历信息id',
               existing_nullable=False)
    op.alter_column('map_points', 'longitude',
               existing_type=mysql.FLOAT(),
               comment='履历信息id',
               existing_nullable=False)
    op.drop_index('ix_map_points_id', table_name='map_points')
    op.drop_column('map_points', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_points', sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
    op.create_index('ix_map_points_id', 'map_points', ['id'], unique=False)
    op.alter_column('map_points', 'longitude',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='履历信息id',
               existing_nullable=False)
    op.alter_column('map_points', 'latitude',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='履历信息id',
               existing_nullable=False)
    op.alter_column('map_points', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='履历信息id',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('map_points', 'height')
    op.drop_column('map_points', 'note')
    op.drop_column('map_points', 'country_name')
    op.drop_column('map_points', 'spot_name')
    # ### end Alembic commands ###
